### ISSUE TITLE
Images workflow - return issues

### ISSUE THREAD

**Issue by Maxfavier** [narendra-addweb/MyImmoPix#158]
From the first tests we conducted we observed an issue. This is its description.

The test was done on a project with 6 images and where 5 images were attributed a credit for edition.

First, an email was received by the client (me). As you can see, there are 2 of them (indicating something is double), and the format is wrong. Link was not working

![email2](https://cloud.githubusercontent.com/assets/17143257/14876843/717463a4-0d18-11e6-9694-cf66be9c2231.png)

When checking the "closed project", I see a project with 15 images. 
When selecting it, I get to the following URL, which is a 404:
http://www.myimmopix.com/order-72017.zip

<img width="1126" alt="project" src="https://cloud.githubusercontent.com/assets/17143257/14876787/15ce553c-0d18-11e6-83dc-307b25ee5827.png">

After checking with Sylvain, the URL should be: 
http://www.myimmopix.com/wp-content/uploads/uploadedzip/order-72017.zip

This URL was working and the zip file was downloaded. (The URL structure is also not ideal as it gives the structure of the site)
However, the zip file structure has many subsequent folders, namely:
srv/www/myImmoPix/wp-content/uploads/final-edited-images/2016/04
This zip file contained the 5 edited images as expected.
This is not practical and also gives an idea of the server structure, which is not a good idea.

Coming back now to the media library, I see 21 images based on the original 6.

<img width="1069" alt="library" src="https://cloud.githubusercontent.com/assets/17143257/14876881/bf1ec040-0d18-11e6-9651-7fad75c6ff7b.png">

There is apparently an action, I think due to Retina, that creates copies of images with different resolutions.

Overall the folder in "closed project" should contain 11 images: 6 original images and 5 edited, and the link that is sent should allow the download of the 5 edited ones.

Let me know if there are some questions or precision needed for this issue.

**Comment by Krina-Addweb** [comment]
@narendra-addweb 
![image](https://cloud.githubusercontent.com/assets/14847553/14935592/e1c4abd6-0ef4-11e6-922a-7d3804d7a0dc.png)
still the functionality is not working correctly.

**Comment by narendra-addweb** [comment]
Hi Maxime,
Please find attached [GIT#158.zip](https://github.com/narendra-addweb/MyImmoPix/files/246422/GIT.158.zip) file and place it as per below instruction.

**1)** downloadimg.php - Place this file into root of your website
**2)** check-change-image-status.php - Place this file into root of your website
**3)** functions.php - Place this file under "wp-content/themes/adrenalin/"
**4)** sidebar-closedpdetail.php - Place this file under "wp-content/themes/adrenalin/"Mail related issue done.

This functionality send two mail, one to client and second to site admin with project related content and page link.

I check but I can't able reproduce it my end so I need to check in deep for solution.

Regarding ZIP, I fixed many subsequent folders issue for download zip. This zip file contained the edited images only.

Yes, Retina creating multiple with different resolutions file for display into different pages.

Current functionality working as like display All original and edited images. ​

Thanks!

**Comment by Maxfavier** [comment]
I still get issues.
For instance, this project just completed I see 15 images in the "closed project" (which is 10 too much) plus I get a 404 (following this URL: http://www.myimmopix.com/order-72107.zip) when I click on it.

<img width="1173" alt="capture d ecran 2016-05-04 08 15 50" src="https://cloud.githubusercontent.com/assets/17143257/15006392/b0ddeda0-11d0-11e6-90f8-7a76eca1f152.png">

Also in the email I get a link that sends me to the "uploaded projects" and not the "closed projects". In addition, there is no direct download link in this.

**Comment by Maxfavier** [comment]
Another issue found with the return script is that it does not run on images from other languages.
For instance, this images have been submitted and brought back to the right place, but did not have their status changed.
<img width="877" alt="capture d ecran 2016-05-04 13 07 45" src="https://cloud.githubusercontent.com/assets/17143257/15012645/ad0d8b84-11fa-11e6-96d9-75af4304c791.png">

For example: http://www.myimmopix.com/wp-content/uploads/2016/05/1462269072-bien11.jpg

is found where it should afterwards:

www.myimmopix.com/wp-content/uploads/final-edited-images/2016/05/1462269072-bien11.jpg

**Comment by narendra-addweb** [comment]
Hi Maxime,
Please find attached [GIT-158.zip](https://github.com/narendra-addweb/MyImmoPix/files/248859/GIT-158.zip) file and place it as per below instruction.

**1)** content-closed-project-detail.php - Place this file under "wp-content/themes/adrenalin/"
**2)** check-change-image-status.php - Place this file into root of your website
**3)** functions.php - Place this file under "wp-content/themes/adrenalin/"
**4)** sidebar-closedpdetail.php - Place this file under "wp-content/themes/adrenalin/"Mail related issue done.
 ​
Let me know once you upload above files so I can check it over live site.
NOTE: Make sure "check-change-image-status.php" file should be with 644 permission.

Thanks!

**Comment by Maxfavier** [comment]
File is installed, we're running tests as well.

**Comment by narendra-addweb** [comment]
Hi Maxime,

I checked this "I get a 404" issue over live(www.myimmopix.com), upload below listed files from attached [GIT-158-1.zip](https://github.com/narendra-addweb/MyImmoPix/files/251688/GIT-158-1.zip).

**1)** check-change-image-status.php- Place this file into root of your website
**2)** downloadimg.php- Place this file into root of your website
**3)** functions.php - Place this file under "wp-content/themes/adrenalin/"
**4)** sidebar-closedpdetail.php - Place this file under "wp-content/themes/adrenalin/"
**5)** content-closed-project-detail.php - Place this file under "wp-content/themes/adrenalin/"

NOTE: Make sure "check-change-image-status.php" and  "downloadimg.php" file should be with 644 permission.

Thanks!

**Comment by Maxfavier** [comment]
Hi Narendra,

We see good progress now. Few items are still an issue on that one.

What works:
- The links sent by email work, the zip is properly downloaded with the right images
- The 404 issue is over; one can access all his projects, included the closed ones.

What does not work:
- Although images were sent from the FR version, the email received was in ENG.
- When in the closed project, we see double images (see screenshot 1).
- When downloading one image from the "closed project" we receive the file but as a 0 octet file, so unusable (see screenshot 2/)

1/
<img width="502" alt="capture d ecran 2016-05-09 17 33 32" src="https://cloud.githubusercontent.com/assets/17143257/15118394/47758c16-160c-11e6-966d-927a8ca889c4.png">

2/
![capture d ecran 2016-05-09 17 35 54](https://cloud.githubusercontent.com/assets/17143257/15118469/93b4422a-160c-11e6-823c-f683af419b16.png)

**Comment by narendra-addweb** [comment]
Hi Maxime,

Please check my below comment:

**1)** Although images were sent from the FR version, the email received was in ENG.
- Ok, Please provide content for FR and NL language.

**2)** When in the closed project, we see double images
- I noticed that order id is different for all double images so this not double images issue. I think you have selected same images for other orders. Please check and let me know.

**3)** When downloading one image from the "closed project" we receive the file but as a 0 octet file, so unusable
- I noticed that this was working fine till yesterday from our end. Let me know if you have made any permission changes OR file code changes.

Thanks!

**Comment by Maxfavier** [comment]
Hello Narendra,

1/
[email - ENG.docx](https://github.com/narendra-addweb/MyImmoPix/files/256951/email.-.ENG.docx)
[email - FR.docx](https://github.com/narendra-addweb/MyImmoPix/files/256953/email.-.FR.docx)
[email - NL.docx](https://github.com/narendra-addweb/MyImmoPix/files/256952/email.-.NL.docx)

**Comment by Maxfavier** [comment]
2/ Will check by uploading new images with singular name. 
You're right that some images were used through different project for test purposes. I will let you know what this test brings.

**Comment by narendra-addweb** [comment]
Hi Maxime,

Please refer [GIT-161](https://github.com/narendra-addweb/MyImmoPix/issues/161).

QA is pending from our-end for now due to our development server is in upgrade process. So please provide you input(s).

Thanks!

**Comment by Maxfavier** [comment]
Hello Narendra,

Thanks for 161, Sylvain is checking it shortly.

So from the test I've run today using 6 images with unique names, never used on the site, I'm getting again the issue in the "closed folder".
Interestingly, the number of pictures at the end is 21, with some present as double, some as triple, etc...

![capture d ecran 2016-05-10 17 01 24](https://cloud.githubusercontent.com/assets/17143257/15151341/00856eaa-16d1-11e6-9f2d-706009cb46dc.png)
![capture d ecran 2016-05-10 17 01 56](https://cloud.githubusercontent.com/assets/17143257/15151342/02c5fa54-16d1-11e6-895d-54a7000d3dc7.png)

**Comment by Maxfavier** [comment]
3/ It works in ENG but not in FR
(test conducted with all newest updates integrated)

**Comment by Maxfavier** [comment]
Following the install of a correction this afternoon, I have again the double images.
But this time I don't see originals in the "closed project" (tested in FR)

![capture d ecran 2016-05-10 17 35 02](https://cloud.githubusercontent.com/assets/17143257/15152734/ad6e5d98-16d6-11e6-9c91-9052a4f6957f.png)

**Comment by Maxfavier** [comment]
I have repeated the previous test: same thing, the project has double images and the originals are not visible anymore.

**Comment by Krina-Addweb** [comment]
Hello Maxime,

Please Find below attached inputs for this issue ::
1) We are unable to find the double image issue, So can you please elaborate the case or steps.
2) Please Check Mail Templates with different languages over live site. 
3) And also for now, we are working on download image & zip issue which occurred with other than english languages.

Thanks

**Comment by Maxfavier** [comment]
Hello Krina,

1/ Did you try it on the live site ? I've put enough example in this thread to show the issue. Also accessing the Media library on prod site will show the presence of double images. 

Please confirm you have a full access to prod site.

**Comment by Maxfavier** [comment]
1/ In addition, a colleague of mine experienced the same issue of double images in closed project both in FR and ENG

**Comment by Maxfavier** [comment]
2/ How can I check the email templates ? By making an order or are they visible somewhere in the Dashboard ?

**Comment by Maxfavier** [comment]
3/ Great, thanks.
